name: Deploy

on:
  workflow_dispatch:
  push:
    workflow_dispatch:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              cd /home/ubuntu/defisaver-forkooor &&
              git checkout main &&
              git fetch --all &&
              git pull origin main &&
              npm i &&
              pm2 stop forkooor &&
              pm2 start forkooor
              '
